### PR TITLE
Added Simplified Chinese Localization

### PR DESCRIPTION
**Pull request by Samekichi**
Screenshots for the config screen and in-game display can be found [here](https://imgur.com/a/OFiwEGH).

**Some notices about translation:**
1. `mod_compatibility` category in the config screen seems to have a display issue and miss some strings , but those strings have been added to my `zh_cn.json` lang file and are translated, including: 
- line 40: `"text.autoconfig.the_bumblezone-main.category.mod.compatibility":"模组兼容",` = mod compat
- line 66: `"text.autoconfig.the_bumblezone-main.option.BZModCompatibilitynConfig.allowPotionOfBeesCompat":"兼容蜜蜂药水",` = be compatible with potion of bees
- and line 67: `"text.autoconfig.the_bumblezone-main.option.BZModCompatibilitynConfig.allowSplashPotionOfBeesCompat":"兼容喷溅型蜜蜂药水",` = be compatible with splash potion of bees

2. I add some format codes to highlight phrases such as `Bumblezone` and `Wrath/Protection of the Hive` for a better readability. If it's not what you want I can delete them :D

3. I've adjusted the examples listed in the description of `absorptionBoostLevel` option based on the mechanism of absorption in Minecraft wiki, but they are only in theory and I cannot test them because of issue#1 mentioned below. 

**Some issues I've encountered:**
1. The range of value for `absorptionBoostLevel`/`speedBoostLevel`/`strengthBoostLevel` in the config screen are extremely large, making it impossible to set a reasonable value. Changing value directly in the config file seems not to work properly as well, both making testing of notice#3 impossible. 

2. Bees in the Bumblezone are likely to bring severe lag, with tps down to about 8.0 on my i7-8750H when only less then 10 bees are loaded. I guess it's because every bee's checking whether mobs within their large detect radius are bringing Bumblezone effects.

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
Awesome thank! i'll take a look into these stuff.

As for the bee lag thing, that's actually due to vanilla's bee AI. It horrible on pathfinding for flying creatures and since The Bumblezone spawns a good deal of bees, it causes lag but there's really nothing I can do about it. If I reduce the bee spawnrates even more, it'll become super hard to find any bee. Even right now, there's something like 100+ bees that spawns (which you can check with /kill @e[type=bee] ) and yet, I can only find like a few of them when exploring due to the fact bees can spawn anywhere in the 0-255 range and in caves too. 

I hope someone can make a mob AI optimization mod that helps reduce bee lag.

**Comment by Samekichi** [comment]
Agree with you lol. Many vanilla mobs' AI are confusing and kind of buggy (hey villagers)

**Comment by TelepathicGrunt** [comment]
Ok so the status effect for the configs was actually off by 1 lol. So absorption was really giving 8 extra health but that's been corrected now.

I also changed a sentence for the absorption lang so I'm letting you know this in case you want to adjust the Chinese translation of that. "For example, Absorption 1 here makes bees get 4 extra padding of health (or 2 full hearts)." And I did fix the mod compat lang entries that weren't working.

Otherwise, let me know if it's all good to go!

**Comment by Samekichi** [comment]
I wish I update zh_cn file in the correct way cuz I'm still new to version control. If so then my part is ready!

**Comment by TelepathicGrunt** [comment]
Thank you! You did update it correctly.I'll merge it now.

Also, I did find that Lithium mod will help optimize the bee's pathfinding so try that mod on with The Bumblezone and it should run quite a bit smoother

**Pull request merged**
