### PR TITLE
Fix for bees eat anything 1.16

### PR DESCRIPTION
**Pull request by genfar1980**
I have added the fix for bees eat anything bug on 1.16 and built it into a jar file that I have tested on my own server.
[zipped_up_jar.zip](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/7025548/zipped_up_jar.zip)
The jar is in the attached zip file

Edit:  forgot to mention its the Fabric version of the mod.
Edit+  seems it says i want to merge 21 commits but seems i messed up on the making of this pull request   as I only changed the code for fixxing the bees eating anything, making it only eat what is in the feeding tag   sorry never did a pull request before.

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
This pr doesnt seem correct. instead of just fixing 1 line of code, this is touching 121 files and looks like it would blow up actually. I went ahead and tried setting up the 1.16 workspace and do a proper fix and upload

**Comment by genfar1980** [comment]
All i did was add a ! to one line in the jar file  like i said I messed up on making the pull request as it was saying I was trying to alter multiple lines when all i changed was one line in BeeInteractivity.java

**Comment by genfar1980** [comment]
Ok so i get what happened, I should not have made a pr request for wanting to give a jar file, because github thought i was trying to pull all of the current release into 1.16 aka the problem with making the title or   1.16 from current release   but also I did not make any changes to anything on github, my zip file has a jar file in it that i compiled using gradle from importing the 1.16 data from here to my pc.   So i probly should have figured out another way to try and give you the jar file than make a pull request because it made it look like i was trying to pull all the current 1.17 files to 1.16 when I was just trying to find a way to give the jar file I made and tested on my own server ( yes i spent like several hours on my own server with the jar file I made making sure it fixxed the problem and not breaking anything else in the process. )

**Comment by TelepathicGrunt** [comment]
Dont worry about it lol. I already gave it a shot and uploaded the fix. Try v2.4.11 Bumblezone for 1.16.5 and see if that works for you

**Comment by genfar1980** [comment]
Naw it works   like the one i did worked but i noticed your sound files for the one you uploaded was smaller in size vs the old 1.16.5 version, so I did  take and put the one you made also on my servef and it works as far as i can tell.   Issue is right now think curseforge having some problems cause some mods for my modpack are not going into the manifest file and instead putting them in the override mod folder   and the ones thats going in there are from the curseforge site not anything i did custom to those.  Any how it took me a while to figure out the gradle thing, so it was a good learning experiance seeing I am trying to learn java more than just able to notice some things or alter stuff.  Anyhow thanks again

**Pull request closed without merging**
